### ISSUE TITLE
Null check on context.showToast(...)

### ISSUE THREAD

**Issue by ynlvko** [sososdk/flash#68]
When I do `context.showToast(Text('Hello'));` I get
```
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      Toast.show (package:flash/flash_helper.dart:51:58)
#1      ToastShortcuts.showToast (package:flash/flash_helper.dart:241:18)
```

which refers to the `context.findAncestorStateOfType<_ToastState>()!`.

What is the proper way to use `context.showToast`/`Toast.show`?

**Comment by ynlvko** [comment]
I've resolved the issue.

I've found the following code in the Example project:
```
MaterialApp(
  navigatorKey: navigatorKey,
  builder: (context, _) {
    var child = _!;
    child = DevicePreview.appBuilder(context, _);
    // Wrap with toast.
    child = Toast(child: child, navigatorKey: navigatorKey);
    return child;
  },
```

Buy I use `MaterialApp.router` with `AutoRoute`, so I had to pass `navigatorKey` to my router's `super.navigatorKey`.

```
final navigatorKey = GlobalKey<NavigatorState>();
final appRouter = AppRouter(navigatorKey: navigatorKey);

@AutoRouterConfig(
  replaceInRouteName: 'Page,Route',
)
class AppRouter extends $AppRouter {
  AppRouter({super.navigatorKey});
  ...
```
